name: remont_kz
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  motion_toast: ^2.7.8
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  pinput: ^2.0.0
  js: ^0.6.2
  mask_text_input_formatter: ^2.0.0
  equatable: ^2.0.5
  carousel_slider: ^4.2.1
  fluttertoast: ^8.2.1
  image_picker: ^0.8.5+3
  web_socket_channel: ^2.4.0
  dots_indicator: ^3.0.0
  stomp_dart_client: ^0.4.4
  get: ^4.6.5
  local_auth: ^2.1.6
  flutter_secure_storage: ^5.0.2
  open_filex: ^4.3.2
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.5.3+2
  table_calendar: ^3.0.8
  retrofit: ^3.0.1+1
  retrofit_generator: ^4.0.3+1
  flutter_launcher_icons: ^0.9.3
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  flutter_native_splash: ^2.2.7
  cached_network_image: ^3.2.1
  lottie: ^1.4.2
  bottom_nav_layout: ^3.0.9
  google_fonts: ^3.0.1
  shared_preferences: ^2.1.1
  provider: ^6.0.2
  get_it: ^7.6.0
  core:
    path: shared/core
  dependencies:
    path: shared/dependencies

flutter_native_splash:
  color: "#018FE2"
  image: assets/images/g10.png
  android: true
  ios: true
  web: true
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "icon"
  image_path: "assets/icons/icon.png"
  background_color: "#009FDC"


flutter_icons:
  image_path: "assets/icons/icon.png"
  android: "launcher_icon"
  ios: true
flutter:

  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/


flutter_intl:
  enabled: true
