name: remont_kz
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  page_transition: ^2.0.9
  connectivity_plus: ^2.3.7
  image_picker: ^0.8.5+3
  flutter_rating_bar: ^4.0.1
  table_calendar: ^3.0.8
  retrofit: ^3.0.1+1
  retrofit_generator: ^4.0.3+1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  flutter_native_splash: ^2.2.7
  cached_network_image: ^3.2.1
  adaptive_dialog: ^1.8.0
  icons_launcher: ^2.0.4
  lottie: ^1.4.2
  bottom_nav_layout: ^3.0.9
  context_menus: ^1.0.2
  flutter_chat_ui: ^1.6.4
  package_info_plus: ^1.4.3+1
  scroll_to_index: ^3.0.1
  url_launcher: ^6.1.5
  google_fonts: ^3.0.1
  intl_phone_field: ^3.1.0
  provider: ^6.0.3
  freezed: ^2.1.1
  core:
    path: shared/core
  dependencies:
    path: shared/dependencies

flutter_native_splash:
  color: "#018FE2"
  image: assets/images/g10.png
  android: true
  ios: true
  web: true
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/


flutter_intl:
  enabled: true
