library dependencies;

export 'package:carousel_slider/carousel_slider.dart';
export 'package:dartz/dartz.dart' hide State, id;
export 'package:dio/dio.dart';
export 'package:equatable/equatable.dart';
export 'package:firebase_core/firebase_core.dart';
// export 'package:firebase_crashlytics/firebase_crashlytics.dart';
// export 'package:firebase_messaging/firebase_messaging.dart';
// export 'package:firebase_remote_config/firebase_remote_config.dart';
export 'package:flutter_bloc/flutter_bloc.dart';
export 'package:formz/formz.dart';
export 'package:get_it/get_it.dart';
export 'package:hive/hive.dart';
export 'package:hive/src/hive_impl.dart';
export 'package:image_picker/image_picker.dart';
export 'package:intl/intl.dart';
export 'package:path_provider/path_provider.dart';
export 'package:rxdart/rxdart.dart';
export 'package:app_links/app_links.dart';
export 'package:connectivity_plus/connectivity_plus.dart';
export 'package:appmetrica_sdk/appmetrica_sdk.dart';
export 'package:carousel_slider/carousel_slider.dart';
export 'package:auto_route/auto_route.dart';
export 'package:flutter_screenutil/flutter_screenutil.dart';
// export 'package:fluttertoast/fluttertoast.dart';
export 'package:package_info_plus/package_info_plus.dart';
export 'package:connectivity_plus/connectivity_plus.dart';
export 'package:url_launcher/url_launcher.dart';
export 'package:external_app_launcher/external_app_launcher.dart';
export 'package:auto_route/auto_route.dart';
// export 'package:flutter_native_splash/flutter_native_splash.dart';
// export 'package:flutter_inappwebview/flutter_inappwebview.dart';
export 'package:app_tracking_transparency/app_tracking_transparency.dart';
export 'package:pretty_dio_logger/pretty_dio_logger.dart';
export 'package:flutter_svg/svg.dart';
export 'package:shimmer/shimmer.dart';
