name: dependencies
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  flutter_bloc: ^7.1.0
  formz: ^0.4.1
  hive: ^2.2.3
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11
  intl: ^0.17.0
  carousel_slider: ^4.1.1
  app_links: ^3.2.0
  app_tracking_transparency: ^2.0.2+4
  appmetrica_sdk: ^0.0.7+1
  auto_route: ^4.0.1
  bottom_sheet: ^2.1.0
  connectivity_plus: ^2.2.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  dotted_border: ^2.0.0+1
  email_validator: ^2.0.1
  equatable: ^2.0.3
  expandable: ^5.0.1
  external_app_launcher: ^2.0.2
#  flutter_inappwebview: ^5.3.2
#  flutter_native_splash: ^2.1.6
  flutter_screenutil: ^5.5.3+2
  flutter_secure_storage: ^5.0.2
  flutter_slidable: ^0.6.0

  geolocator: ^7.6.2
  get_it: ^7.2.0
  graphql_flutter: ^5.0.0
  in_app_review: ^2.0.4
  modal_bottom_sheet: ^2.0.1
  package_info_plus: ^1.3.0
#  permission_handler: ^8.1.6
  pinput: ^2.2.11
  pretty_dio_logger: ^1.1.1
  provider: ^6.0.2
  recase: ^4.0.0
  rxdart: ^0.27.3
  scroll_to_index: ^3.0.1
  share_plus: ^4.0.4
  shared_preferences: ^2.0.7
#  url_launcher: ^6.0.10
  flutter_svg: ^1.1.4
  shimmer: ^2.0.0

  # firebase
#  firebase_analytics: ^9.0.3
  firebase_core: ^1.10.5
#  firebase_remote_config: ^2.0.12
#  firebase_messaging: ^11.2.5
#  firebase_crashlytics: ^2.5.3
#  firebase_in_app_messaging: ^0.6.0+24



dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter

flutter: null
